### ISSUE TITLE
Not Able to Download the PDF

### ISSUE THREAD

**Issue by dilipwk** [lizardmedia/product-attachments-magento2#10]
PDF added in admin side successfully and also in end user front end its showing under attachments but when I click on file name to download its redirecting to http:// base-url /downloadable/download/attachment/id/1/ and then redirecting to product page but No pdf attachment downloaded.

**Comment by bartoszkubicki** [comment]
@dilipwk I will try to reproduce it and come back with some questions in case I won't be able to do so.

**Comment by bartoszkubicki** [comment]
@dilipwk I need information what is your configuration value for field `links_target_new_window` and if this file is uploaded as file or url

**Comment by bartoszkubicki** [comment]
@dilipwk It is two week since last reply. For now I assume that problem is gone. If not and you have any more tips to reproduce issue feel free to repopen issue.

**Comment by dilipwk** [comment]
Yes, it's working it was not accepting some demo pdf when I created pdf myself its working fine.
