### ISSUE TITLE
Add support for 7.2

### ISSUE THREAD

**Issue by bartoszkubicki** [lizardmedia/product-attachments-magento2#11]
Along with refactor support for php 7.2 should be provided.

**Comment by younes0** [comment]
hello @bartoszkubicki is the module compatible with 7.2 ?

**Comment by bartoszkubicki** [comment]
@younes0 It was written quite some time ago and for that time there was support for 7.1. As you see (issue created) we are going to add support for 7.2 along with refactor. Although, I have just looked into php 7.2 features and I think extension should work on php 7.2.

**Comment by younes0** [comment]
Yes it does work with PHP 7.2 and Magento 2.3.3
Could you update the composer.json PHP requirement ? https://github.com/lizardmedia/product-attachments-magento2/pull/12
