### ISSUE TITLE
Can't attach a file

### ISSUE THREAD

**Issue by FrancescoTalotta** [lizardmedia/product-attachments-magento2#22]
Hello,

I installed the plugin but when I attach a file I get an error in the webpage: 

"A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later." 

and no file is attached.

Francesco

**Comment by bartoszkubicki** [comment]
Hello @FrancescoTalotta, I have a few questions:

1. Do you have the newest plugin version?
2. Does this problem occured in admin page, while uploading file?
3. If question 2 is correct, could you try again with dev tools console open and look for any error?
4. It is possible that you are uploading too big file - limitations are in php/nginx configuration. You should see an error in dev console. If it is not this, I will ask more question, please try this path for now.

**Comment by FrancescoTalotta** [comment]
Hello,

yesterday I installed the plugin with composer. In the composer.json file it says version 1.3.1.  The error appears in the product page and the file I tried to upload was ~170kb. In `php.ini` I have 
`memory_limit=512M`, `upload_max_filesize=128M`, `post_max_size=8M`. I don't use `nginx` but apache2 so i guess I don't need to set the `client_max_body_size`. In the dev console I have some errors:

`jquery.js:10260 POST https://www.project-a320.com/index.php/admin_fk15to/admin/attachment_file/upload/attachment_type/attachments/key/fcd6ebdee387cc7151a3ace3bff03b5bd8d01e8fd00009fa3e276dae0cc880d8/?isAjax=true 404 (Not Found)`


`in file file-uploader.js:41`
```
<!doctype html>
<html lang="en">
    <head >
        <script>
    var BASE_URL = 'https://www.project-a320.com/index.php/admin_fk15to/admin/index/index/key/43efda09c31379b8607098f99709f4468c50b0f335da70868e2e2b586b7a4ea7/';
    var FORM_KEY = '0HDdNgU9JTeBVRrb';
    var require = {
        "baseUrl": "https://www.project-a320.com/pub/static/version1584269851/adminhtml/Magento/backend/en_US"
    };
</script>
        <meta charset="utf-8"/>
<meta name="title" content="Project A320 Magento Admin"/>
<meta name="description" content="Your Own Airbus A320 Cockpit at home"/>
<meta name="robots" content="NOINDEX,NOFOLLOW"/>
<meta name="viewport" content="width=1024"/>
<meta name="format-detection" content="telephone=no"/>
<title>Project A320 Magento Admin</title>
<link  rel="stylesheet" type="text/css"  media="all" href="https://www.project-a320.com/pub/static/version1584269851/adminhtml/Magento/backend/en_US/extjs/resources/css/ext-all.css" />
<link  rel="stylesheet" type="text/css"  media="all" href="https://www.project-a320.com/pub/static/version1584269851/adminhtml/Magento/backend/en_US/extjs/resources/css/ytheme-magento.css" />
<link  rel="stylesheet" type="text/css"  media="all" href="https://www.project-a320.com/pub/static/version1584269851/adminhtml/Magento/backend/en_US/jquery/jstree/themes/default/style.css" />
<link  rel="stylesheet" type="text/css"  media="all" href="https://www.project-a320.com/pub/static/version1584269851/adminhtml/Magento/backend/en_US/css/styles-old.css" />
<link  rel="stylesheet" type="text/css"  media="all" href="https://www.project-a320.com/pub/static/version1584269851/adminhtml/Magento/backend/en_US/css/styles.css" />
<link  rel="stylesheet" type="text/css"  media="all" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
<script  type="text/javascript"  src="https://www.project-a320.com/pub/static/version1584269851/adminhtml/Magento/backend/en_US/requirejs/require.js"></script>
<script  type="text/javascript"  src="https://www.project-a320.com/pub/static/version1584269851/adminhtml/Magento/backend/en_US/mage/requirejs/mixins.js"></script>
<script  type="text/javascript"  src="https://www.project-a320.com/pub/static/version1584269851/adminhtml/Magento/backend/en_US/requirejs-config.js"></script>
<link  rel="icon" type="image/x-icon" href="https://www.project-a320.com/pub/media/favicon/stores/1/favicon_2_1.png" />
<link  rel="shortcut icon" type="image/x-icon" href="https://www.project-a320.com/pub/media/favicon/stores/1/favicon_2_1.png" />
            </head>
    <body data-container="body"
          data-mage-init='{"loaderAjax": {}, "loader": { "icon": "https://www.project-a320.com/pub/static/version1584269851/adminhtml/Magento/backend/en_US/images/loader-2.gif"}}'
        id="html-body" class="adminhtml-noroute-index page-layout-admin-1column">
        <div class="menu-wrapper">                        <a
            href="https://www.project-a320.com/index.php/admin_fk15to/admin/"
            data-edition="Community Edition"            class="logo">
            <img class="logo-img" src="https://www.project-a320.com/pub/static/version1584269851/adminhtml/Magento/backend/en_US/images/magento-icon.svg"
            alt="Magento&#x20;Admin&#x20;Panel" title="Magento&#x20;Admin&#x20;Panel"/>
        </a>

<nav data-mage-init='{"globalNavigation": {}}' class="admin__menu">
    <ul id="nav" role="menubar" ><li  data-ui-id="menu-magento-backend-dashboard"  class="item-dashboard    level-0" id="menu-magento-backend-dashboard" aria-haspopup="true" role="menu-item"><a href="https://www.project-a320.com/index.php/admin_fk15to/admin/dashboard/index/key/982a3e4d987bb48700c8e136f85cd564268b6a815885bd3a701313f17b83c75b/"   class=""><span>Dashboard</span></a></li><li  data-ui-id="menu-magento-sales-sales"  class="item-sales  parent  level-0" id="menu-magento-sales-sales" aria-haspopup="true" role="menu-item"><a href="#"   onclick="return false;" class=""><span>Sales</span></a><div class="submenu" aria-labelledby="menu-magento-sales-sales"><strong class="submenu-title">Sales</strong><a href="#" class="action-close _close" data-role="close-submenu"></a><ul role="menu" ><li  data-ui-id="menu-magento-sales-sales-operation"  class="item-sales-operation  parent  level-1" role="menu-item"><strong class="submenu-group-title" role="presentation"><span>Operations</span></strong><div class="submenu"><ul role="menu" ><li  data-ui-id="menu-magento-sales-sales-order"  class="item-sales-order    level-2" role="menu-item"><a href="https://www.project-a320.com/index.php/admin_fk15to/sales/order/index/key/4f636fa95a6dfff359735d0e2295bc9d920c552bbd36e7053a5634953c96cf96/"   class=""><span>Orders</span></a></li><li  data-ui-id="menu-magento-sales-sales-invoice"  class="item-sales-invoice    level-2" role="menu-item"><a href="https://www.project-a320.com/index.php/admin_fk15to/sales/invoice/index/key/dc63a8c2fc12bcd35b3088845a05cca1b544f4f4d88856fde40987e111c87dd1/"   class=""><span>Invoices
```

**Comment by bartoszkubicki** [comment]
@FrancescoTalotta It is something wrong with this path, there is no controller like this in our module. Can add some screen, where do you click?

**Comment by FrancescoTalotta** [comment]
@bartoszkubicki I'm using Mac Os X. The path is:

`/Users/francesco/Documents/Store/ECAM/ECAM_PANEL_Drawing_v3.pdf`

Is that what you asked? 

Thank you

**Comment by bartoszkubicki** [comment]
No I meant path from `jquery.js:10260 POST https://www.project-a320.com/index.php/admin_fk15to/admin/attachment_file/upload/attachment_type/attachments/key/fcd6ebdee387cc7151a3ace3bff03b5bd8d01e8fd00009fa3e276dae0cc880d8/?isAjax=true 404 (Not Found)`. But I see that there is admin contoller, which can have path like this. Can you share screen where you show what exactly do you click? Module has been upgrade heavily last time, so everything should work. Please post magento version you use.

**Comment by FrancescoTalotta** [comment]
I use Magento ver. 2.3.4
I'm still not sure about what you mean by share screen where I click. Do you want screenshot of the dev console output?

**Comment by bartoszkubicki** [comment]
I mean screen where I can see where excatly do you click. Last week I didn't encoutered such an issue on clean magento install.

**Comment by FrancescoTalotta** [comment]
In the product page I expand `Product attachments`  then I click on `Add attachment`, then `Browse Files...` and then when I select the file and click `Open` I get the error I wrote to you on the first page, and no file is uploaded.

**Comment by bartoszkubicki** [comment]
That's strange, we use this module in one of our project we work on right now and everything is ok? Do you think you can have any module which can interrupt this module? Do you have Magento_Downloadable present and enabled?

**Comment by FrancescoTalotta** [comment]
Yes, it's there, present and enabled

**Comment by bartoszkubicki** [comment]
Ok I will test it in a few days on clean 2.3.4 magento install. I will reach you back next week.

**Comment by bartoszkubicki** [comment]
@FrancescoTalotta I acknowledge bug. Solution will be released in 1.3.2. Thank you for your input.

**Comment by FrancescoTalotta** [comment]
Ok,

hope it will be released ASAP. :) 

Thank you

**Comment by bartoszkubicki** [comment]
@FrancescoTalotta please update your package to the newest version https://github.com/lizardmedia/product-attachments-magento2/releases/tag/1.3.2 and let me know here if now everything works as expected.

**Comment by FrancescoTalotta** [comment]
Hello,

now I can attach the file. However I can't download the file. When I click on it, the webpage simply redirects me on the same product page...I guess you can try by yourself to click on it:

[https://www.project-a320.com/index.php/a320-switching-panel.html](url)

**Comment by bartoszkubicki** [comment]
@FrancescoTalotta I have just tested module on 2.3.3 and all seems to work. I will close this issue. If you have a problem please create new one, but first, check read rights to file you have attached on your server.
