### ISSUE TITLE
Do not show for products with no attachments

### ISSUE THREAD

**Issue by kanzelsberger** [lizardmedia/product-attachments-magento2#27]
Wouldn't it be better to not show "Attachments" tab at all if there are none? I tried it in my store and it shows within all products but says "no attachments"...

**Comment by bartoszkubicki** [comment]
Thank you for trying out our module. Yes, maybe it would be better. If you want you can prepare PR. In meanwhile we will put it in out schedule.

**Comment by bartoszkubicki** [comment]
@kanzelsberger  this feature has been introduced in 1.3.5 version. Thanks for contribution.
