### ISSUE TITLE
Tab position

### ISSUE THREAD

**Issue by kanzelsberger** [lizardmedia/product-attachments-magento2#28]
Is it possible to configure Attachments Tab position on product page? Maybe I would like to move the Tab to 2nd or even last position.

**Comment by bartoszkubicki** [comment]
You can move it around using layout xml way by modification of [this file](https://github.com/lizardmedia/product-attachments-magento2/blob/master/view/frontend/layout/catalog_product_view.xml), for example by ordering blocks by before/after attribute
