### ISSUE TITLE
Php parse error

### ISSUE THREAD

**Issue by myselfgaurav** [lizardmedia/product-attachments-magento2#3]
PHP Parse error:  syntax error, unexpected '?' in /app/code/LizardMedia/ProductAttachment/Model/AttachmentRepository.php on line 244

**Comment by maciejslawik** [comment]
Hi,
what PHP version are you using?

**Comment by maciejslawik** [comment]
Sorry, the module has a declared compatibility with PHP 7.1 and higher. 
You can either upgrade or fix the PHP 7.0 incompatibilities yourself, which should be simple.
