### ISSUE TITLE
Attachments div empty

### ISSUE THREAD

**Issue by Carlosvice** [lizardmedia/product-attachments-magento2#34]
@bartoszkubicki Hello Bartosz, today I installed Magento 2.3.3 on a clean OS, first I tried installing your extension`s version 1.3.2 with no luck and then I triend with version 1.3.4, and I`m getting the same issue, I can see the Attachments section on admin panel but it has no content, I checked logs and console, it doesn`t trigger any error Same issue with Magento 2.3.5 as I mentioned before. Hope you can help me out. P.D. I dived into the code and I don`t see anything under the fieldset section of the attachments module. I dont`t know if there`s anything else I could check, I`m using windows server 2012, xampp and chrome.

Thanks a lot!

**Comment by bartoszkubicki** [comment]
@Carlosvice Have you installed it using composer?

**Comment by Carlosvice** [comment]
Thanks for replying! Yes installed it with composer and ran the upgrade also with composer. My procedure was: On a clean WServer 2012 R2 installed all the updates, then installed Xampp with php 7.3.18, then installed Magento 2.3.3 form their archive directly on their page, then installed your extension with the following command: composer require lizardmedia/module-product-attachments:1.3.2. After that ran the module:enable and the setup:upgrade. Checked the functionality, saw I could not see the content and then ran the upgrade for the version 1.3.4 of the extension.

**Comment by bartoszkubicki** [comment]
@Carlosvice I don't have any idea. Windows is not recomended OS for magento, but I don't think this is the case here. While solving your former issue I have tested module against newest magento 2.3 version. It was 2.3.4 then. We have it working on 2.3.3 also Tommorow I will test it against 2.3.5.

**Comment by bartoszkubicki** [comment]
@Carlosvice today we have tested module on magento 2.3.5. We can't reproduce this issue.

**Comment by Carlosvice** [comment]
@bartoszkubicki Hello Bartosz! I know, I'm having other issues, unfortunately my target system is Windows. Thanks a lot for the support, you're very kind. If I manage to resolve the issue I'll let you know.
