### ISSUE TITLE
Issues on WAMP

### ISSUE THREAD

**Issue by b1wan** [lizardmedia/product-attachments-magento2#36]
I have the same issue #34 on WAMP environnement. I know that Magento is not recommended on Windows.

I think there's a problem with the DIRECTORY_SEPARATOR ( "/" on Linux, " \ " on Windows).
On the file vendor\lizardmedia\module-product-attachments\Ui\DataProvider\Product\Form\Modifier\Attachments.php at line 106 : 
`$attachmentsPath = Composite::CHILDREN_PATH . DIRECTORY_SEPARATOR . Composite::CONTAINER_ATTACHMENTS;`
give me "product_attachment/children\container_attachments" instead of "product_attachment\children\container_attachments"

If I do the change, the form appear on admin panel but it doesn't work (the file is uploaded but stay in /tmp directory, no entry on database).

I think there're others issues due to this problem like in this file : lizardmedia\module-product-attachments\Model\Attachment.php
Line 109 : `return 'downloadable/tmp/attachment';`
Line 117 : `return 'downloadable/files/attachment';`

I did not succeed to use the plugin on WAMP but I don't think that's a big deal to do it.

Anyways, thank you for your good work !

**Comment by bartoszkubicki** [comment]
@b1wan Thank you for reporting an issue. If you have already fixed it, please post it as a PR. If not we will try to fix it.

**Comment by bartoszkubicki** [comment]
@b1wan I think piece of code you've mentioned is not really a filesystem path, so I have removed DIRECTORY_SEPARTOR (which should work in case of real filesystem path). https://github.com/lizardmedia/product-attachments-magento2/pulls - this should fix the bug.

**Comment by bartoszkubicki** [comment]
@b1wan Should be fixed, please try

**Comment by b1wan** [comment]
It works on WAMP (Magento 2.3.5), thank you !

The front view tab name on product page is not the text in the field "Title" on admin product page ? (maybe I did not correctly clean the cache)

I update vendor\lizardmedia\module-product-attachments\view\frontend\layout\catalog_product_view.xml to update the tab title (which is not the best if I update the module...)

Anyways, thank you again for your work !

**Comment by bartoszkubicki** [comment]
![image](https://user-images.githubusercontent.com/20238194/99072319-187b3200-25b4-11eb-901b-883f1c8a8ecd.png)
You mean this one?

**Comment by b1wan** [comment]
Yes !

**Comment by bartoszkubicki** [comment]
For now it can be changed, as you said, by layout xml. It is not the top priority right now (two bugs ahead), so if you want you can create PR for this.
