### ISSUE TITLE
Attachments get copied to root upon download

### ISSUE THREAD

**Issue by OvalMedia** [lizardmedia/product-attachments-magento2#37]
Magento: 2.4.1
PHP: 7.3
Module: 1.3.5
Docroot in /pub/

Whenever I download an attached file it will dump a copy of that file in the magento root folder first before allowing the download. In my case the DOCroot is /pub/ but still the files to download end up with a copy in the magento root (where the vendor folder resides). The file dumped is totally inaccessible from the browser so it does not make much sense to put it there. It does not matter if downloaded from frontend or backend, there is always a copy. The download itself works fine though.

Download paths look like this:

Admin
https://www.example.com/admin/downloadable/attachment_file/preview/id/146

Frontend:
https://www.example.com/downloadable/download/attachment/id/102/

**Comment by bartoszkubicki** [comment]
Hi @OvalMedia. It seems like a bug. I will verify it and come back with some information.

**Comment by bartoszkubicki** [comment]
@OvalMedia I can reproduce this issue

**Comment by bartoszkubicki** [comment]
@OvalMedia should be fixed in newest version, please check it

**Comment by OvalMedia** [comment]
Works fine now. Thank you.
