### ISSUE TITLE
Unable to see file attributes yet

### ISSUE THREAD

**Issue by myselfgaurav** [lizardmedia/product-attachments-magento2#4]
![image](https://user-images.githubusercontent.com/1726505/47041019-5c1ccb00-d1a5-11e8-8466-9b0ced7b533c.png)

I have installed modules but can not see option to create attribute type file please help with it

**Comment by bartoszkubicki** [comment]
I think you have misunderstood purpose and usage of module. Please take a look at updated README.md , I have added screenshots.
