### ISSUE TITLE
Compatibility Magento 2.4 / PHP 7.4?

### ISSUE THREAD

**Issue by OvalMedia** [lizardmedia/product-attachments-magento2#42]
When I try to update to Magento 2.4 (running PHP 7.4) composer fails with this error message: "lizardmedia/module-product-attachments 1.3.5 requires php ~7.1.0|~7.2.0|~7.3.0 -> your PHP version (7.4.8) does not satisfy that requirement."

Can you update the module?

**Comment by bartoszkubicki** [comment]
@OvalMedia yes https://github.com/lizardmedia/product-attachments-magento2/pull/40

**Comment by bartoszkubicki** [comment]
Should be fixed in new version 1.3.6
