### ISSUE TITLE
Error when saving a product with existing attachment

### ISSUE THREAD

**Issue by OvalMedia** [lizardmedia/product-attachments-magento2#45]
When I try to save a product with an existing attachment I get this error:
`Item (LizardMedia\ProductAttachment\Model\Attachment) with the same ID "195" already exists.`

I cleaned all lizardmedia* tables to be sure everything is from scratch. I also removed all files in pub\media\downloadable\files\attachment.

Then I uploaded a PDF to an existing product which worked fine. But editing this product afterwards failed with the mentioned error.

**Comment by OvalMedia** [comment]
Sorry, I forgot:

- PHP 7.3
- Magento 2.4.1

**Comment by bartoszkubicki** [comment]
@OvalMedia I will look at this this week. Thank you for reporting this issue.

**Comment by bartoszkubicki** [comment]
@OvalMedia I have reverted change that caused a problem https://github.com/lizardmedia/product-attachments-magento2/commit/676080293bfee87f8655ad372277301170d6c7d5. Please test it

**Comment by OvalMedia** [comment]
Problem is gone. Thank you.

**Comment by mmeyran** [comment]
Hello,
I'm still getting that error with 1.3.8 - the module allows duplicate pairs of attachment_id and store_id in the title table, and it does happen. I have put a constraint on these columns directly in database to not break my front anymore, and I'm adding checks to my own code to prevent these extra insertion attempts, but it still happens with store_id 0.
It would be a good idea to add the constraint to the module itself, though.

**Comment by mmeyran** [comment]
It seems to happen more often if one tries to save the product through the entity manager.
