### ISSUE TITLE
Title not connected correctly

### ISSUE THREAD

**Issue by rofthedeep** [lizardmedia/product-attachments-magento2#46]
Hi,

thx for your work!

I found an issue with storing the title of the attachments.

The attachment is saved:
![Bildschirmfoto 2020-12-21 um 10 49 11](https://user-images.githubusercontent.com/2420176/102763593-30479200-437a-11eb-9a75-b3a85bcb6508.png)

And the title is saved:
![Bildschirmfoto 2020-12-21 um 10 49 02](https://user-images.githubusercontent.com/2420176/102763646-42293500-437a-11eb-9715-7250ac158a15.png)

But the title doesn't show up in the magento backend:
![Bildschirmfoto 2020-12-21 um 10 48 38](https://user-images.githubusercontent.com/2420176/102763696-553c0500-437a-11eb-9ac6-18512116ac83.png)

If I save the attachment again, the the new title is saved but the old one still exists:
![Bildschirmfoto 2020-12-21 um 10 51 06](https://user-images.githubusercontent.com/2420176/102763831-86b4d080-437a-11eb-9adc-1bad94d0fca1.png)

And still does not show up:
![Bildschirmfoto 2020-12-21 um 10 52 13](https://user-images.githubusercontent.com/2420176/102763936-a946e980-437a-11eb-89fc-b895ffd45d00.png)

I'm using Magento 2.3.5 and this is a grouped product.

Best, Tim

**Comment by bartoszkubicki** [comment]
@rofthedeep Thank you for detailed report. I will look at that this wek.

**Comment by rofthedeep** [comment]
> @rofthedeep Thank you for detailed report. I will look at that this wek.

Thank you! :)

**Comment by bartoszkubicki** [comment]
@rofthedeep I have just tested it on magento 2.3.4 (I don't think magento version really matters) for grouped product and it seems to work. Are you sure you have module in the newest version?

**Comment by rofthedeep** [comment]
@bartoszkubicki thx for testing! 
Hmm, I think it has sth to do with using the correct store id. In our case it tries to load the store id 1 but stores with 0. Perhaps this is only an issue in our setup ...

**Comment by bartoszkubicki** [comment]
@rofthedeep do you have single store mode enabled?

**Comment by rofthedeep** [comment]
hi @bartoszkubicki,
I think I found sth:
product-attachments-magento2/Model/ResourceModel/Attachment.php

There you have this function:

` /**
     * @param AttachmentModel $attachment
     * @return Attachment
     */
    public function saveItemTitle(AttachmentModel $attachment): Attachment
    {
        $connection = $this->getConnection();
        $attachmentTitleTable = $this->getTable(AttachmentModel::TITLE_TABLE);
        $bind = [':id' => (int) $attachment->getId(), ':store_id' => (int) $attachment->getStoreId()];

        $select = $connection->select()->from(
            $attachmentTitleTable
        )->where(
            'id = :id AND store_id = :store_id'
        );

        if ($connection->fetchOne($select, $bind)) {
            $where = [
                'id = ?' => (int) $attachment->getId(),
                'store_id = ?' => (int) $attachment->getStoreId(),
            ];
            if ($attachment->getUseDefaultTitle()) {
                $connection->delete($attachmentTitleTable, $where);
            } else {
                $connection->update($attachmentTitleTable, [AttachmentModel::TITLE => $attachment->getTitle()], $where);
            }
        } else {
            if (!$attachment->getUseDefaultTitle()) {
                $connection->insert(
                    $attachmentTitleTable,
                    [
                        AttachmentModel::ATTACHMENT_ID => (int) $attachment->getId(),
                        AttachmentModel::STORE_ID => (int) $attachment->getStoreId(),
                        AttachmentModel::TITLE => $attachment->getTitle()
                    ]
                );
            }
        }

        return $this;
    }`

If I get it correctly, the attachment_id is stored in the id column and not in the attachment_id column. 

I think it has to be like this:


`    /**
     * @param AttachmentModel $attachment
     * @return Attachment
     */
    public function saveItemTitle(AttachmentModel $attachment): Attachment
    {
        $connection = $this->getConnection();
        $attachmentTitleTable = $this->getTable(AttachmentModel::TITLE_TABLE);
        $bind = [': attachment_id' => (int) $attachment->getId(), ':store_id' => (int) $attachment->getStoreId()];

        $select = $connection->select()->from(
            $attachmentTitleTable
        )->where(
            'attachment_id = :attachment_id AND store_id = :store_id'
        );

        if ($connection->fetchOne($select, $bind)) {
            $where = [
                'attachment_id = ?' => (int) $attachment->getId(),
                'store_id = ?' => (int) $attachment->getStoreId(),
            ];
            if ($attachment->getUseDefaultTitle()) {
                $connection->delete($attachmentTitleTable, $where);
            } else {
                $connection->update($attachmentTitleTable, [AttachmentModel::TITLE => $attachment->getTitle()], $where);
            }
        } else {
            if (!$attachment->getUseDefaultTitle()) {
                $connection->insert(
                    $attachmentTitleTable,
                    [
                        AttachmentModel::ATTACHMENT_ID => (int) $attachment->getId(),
                        AttachmentModel::STORE_ID => (int) $attachment->getStoreId(),
                        AttachmentModel::TITLE => $attachment->getTitle()
                    ]
                );
            }
        }

        return $this;
    }`

What do you think about that?
Best, Tim

**Comment by rofthedeep** [comment]
And yes - the single store mode is enabled

**Comment by bartoszkubicki** [comment]
@rofthedeep Thank you fo the tip. I will check it.

**Comment by bartoszkubicki** [comment]
@rofthedeep Checking it quickly on working project with newest version - all works fine. Are you sure you have the newest module version?

**Comment by mokadev** [comment]
Hi

 same problem here The title is saved twice in the table for a same store_id, so when the product loads it fires a exception :

```
Item (LizardMedia\\ProductAttachment\\Model\\Attachment) with the same ID \"7793\" already exists.
#1 Magento\\Framework\\Data\\Collection\\AbstractDb->loadWithFilter() called at [vendor\/magento\/framework\/Data\/Collection\/AbstractDb.php:565]
#2 Magento\\Framework\\Data\\Collection\\AbstractDb->load() called at [vendor\/magento\/framework\/Data\/Collection.php:839]
#3 Magento\\Framework\\Data\\Collection->getIterator() called at [app\/code\/LizardMedia\/ProductAttachment\/Model\/AttachmentRepository.php:216]
#4 LizardMedia\\ProductAttachment\\Model\\AttachmentRepository->getAttachmentsByProduct() called at [app\/code\/LizardMedia\/ProductAttachment\/Model\/Attachment\/ReadHandler.php:47]
#5 LizardMedia\\ProductAttachment\\Model\\Attachment\\ReadHandler->execute() called at [vendor\/magento\/framework\/EntityManager\/Operation\/Read\/ReadExtensions.php:48]
#6 Magento\\Framework\\EntityManager\\Operation\\Read\\ReadExtensions->execute() called at [vendor\/magento\/framework\/EntityManager\/Operation\/Read.php:112]
#7 Magento\\Framework\\EntityManager\\Operation\\Read->execute() called at [vendor\/magento\/framework\/EntityManager\/EntityManager.php:70]
#8 Magento\\Framework\\EntityManager\\EntityManager->load() called at [vendor\/magento\/module-catalog\/Model\/ResourceModel\/Product.php:716]
#9 Magento\\Catalog\\Model\\ResourceModel\\Product->load() called at [vendor\/magento\/framework\/Model\/AbstractModel.php:540]
#10 Magento\\Framework\\Model\\AbstractModel->load() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]
#11 Magento\\Catalog\\Model\\Product\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]
#12 Magento\\Catalog\\Model\\Product\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]
#13 Magento\\Catalog\\Model\\Product\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Catalog\/Model\/Product\/Interceptor.php:50]
#14 Magento\\Catalog\\Model\\Product\\Interceptor->load() called at [vendor\/magento\/module-catalog\/Model\/ProductRepository.php:308]
#15 Magento\\Catalog\\Model\\ProductRepository->getById() called at [vendor\/magento\/module-catalog\/Model\/ProductNotFoundPageCacheTags.php:64]
#16 Magento\\Catalog\\Model\\ProductNotFoundPageCacheTags->process() called at [vendor\/magento\/module-page-cache\/Model\/PageCacheTagsPreprocessorComposite.php:64]
#17 Magento\\PageCache\\Model\\PageCacheTagsPreprocessorComposite->process() called at [vendor\/magento\/module-page-cache\/Model\/Layout\/LayoutPlugin.php:100]
#18 Magento\\PageCache\\Model\\Layout\\LayoutPlugin->afterGetOutput() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:146]
#19 Magento\\Framework\\View\\Layout\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]
#20 Magento\\Framework\\View\\Layout\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php:41]
#21 Magento\\Framework\\View\\Layout\\Interceptor->getOutput() called at [vendor\/magento\/framework\/View\/Result\/Page.php:258]
#22 Magento\\Framework\\View\\Result\\Page->render() called at [vendor\/magento\/framework\/View\/Result\/Layout.php:171]
#23 Magento\\Framework\\View\\Result\\Layout->renderResult() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]
#24 Magento\\Framework\\View\\Result\\Page\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]
#25 Magento\\Framework\\View\\Result\\Page\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]
#26 Magento\\Framework\\View\\Result\\Page\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/View\/Result\/Page\/Interceptor.php:23]
#27 Magento\\Framework\\View\\Result\\Page\\Interceptor->renderResult() called at [vendor\/magento\/framework\/App\/Http.php:120]
#28 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:263]
#29 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:40]
```

**Comment by mokadev** [comment]
Oh boy ... each time you save a product without changing the attached file, the old line in lizardmedia_product_attachment table for the product is deleted and a new one is added...Is it intended?

**Comment by bartoszkubicki** [comment]
@mokadev no it was not intended. However module was written a few years ago and there is no point fixing it, it needs rewriting from the scratch, using more up-to-date products extending solutions.

**Comment by bartoszkubicki** [comment]
merged
