### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Return value of LizardMedia\ProductAttachment\Model\AttachmentRepository::getAttachments()

### ISSUE THREAD

**Issue by martijn-bigbridge** [lizardmedia/product-attachments-magento2#49]
Hi,

We get this error, and now i'm wondering if this is correct
https://github.com/lizardmedia/product-attachments-magento2/blob/29b22677ca4fd4a0e41d0d56e50337b2f548475b/Model/AttachmentRepository.php#L228

Because the error log say this will return a array

```
return $product->getProductAttachments();
```

And here it is a array

https://github.com/lizardmedia/product-attachments-magento2/blob/29b22677ca4fd4a0e41d0d56e50337b2f548475b/Plugin/InitForSave.php#L81

```
PHP Fatal error:  Uncaught TypeError: Return value of LizardMedia\ProductAttachment\Model\AttachmentRepository::getAttachments() must be an instance of LizardMedia\ProductAttachment\Model\ResourceModel\Attachment\Collection or null, array returned in /...../vendor/lizardmedia/module-product-attachments/Model/AttachmentRepository.php:239
Stack trace:
#0 ...../vendor/lizardmedia/module-product-attachments/Model/AttachmentRepository.php(214): LizardMedia\ProductAttachment\Model\AttachmentRepository->getAttachments(Object(Magento\Catalog\Model\Product\Interceptor))
#1 /...../vendor/lizardmedia/module-product-attachments/Model/Attachment/UpdateHandler.php(49): LizardMedia\ProductAttachment\Model\AttachmentRepository->getAttachmentsByProduct(Object(Magento\Catalog\Model\Product\Interceptor))
#2 /var/domains/ in ...../vendor/lizardmedia/module-product-attachments/Model/AttachmentRepository.php on line 239
```

**Comment by bartoszkubicki** [comment]
@martijn-bigbridge Thank you for reporting an issue. Can you provide steps to reproduce this issue? In fact, there is possiblity for this to happen, basing on code snippets provided. However I can' reporduce it neither on frontend nor in adminhtml.

**Comment by martijn-bigbridge** [comment]
@bartoszkubicki 
Sorry, I only have the error message inside the php error log. So I don't know the steps to reproduce it.

**Comment by bartoszkubicki** [comment]
@martijn-bigbridge are you sure that this log is produced by current version of module?

**Comment by martijn-bigbridge** [comment]
@bartoszkubicki 
Sorry I did forget to say that the version is 1.3.5, is it fixed in the latest version ?

**Comment by bartoszkubicki** [comment]
Basing on https://github.com/lizardmedia/product-attachments-magento2/blob/master/CHANGELOG.md I don't fix so, because we didn't meet that error. I tried all paths in module, when this code is run and there was no error - saving product, creating product  with / without attachments, refreshing product page in admin, displayng list of att. on frontend

**Comment by martijn-bigbridge** [comment]
I did ask the client, and maybe it is during a REST api request at night.
I don't know what request it is, but I guess something like get product

**Comment by bartoszkubicki** [comment]
Ok I will try to figure it out or just make sure it is impossible to have type erro

**Comment by bartoszkubicki** [comment]
@martijn-bigbridge I am sorry but I can't reproduce it. I have tried with postman and webapi, getting products' list and individual products, but no sign of error. Make sure you have the newest version and if you have any more details don't hesitate to provide them and feel free to repopen this issue.

**Comment by Parism** [comment]
I get the same error when trying to update product with existing attachment through Magento's REST API.
To be more specific I set product's extension_attributes to have the existing product attachment (the array which I get from loading the product through Magento REST API) and when I post the data to Magento I get the same error mentioned above.
If you post the product's data without setting the existing attachment as it's extension attributes then the attachment gets deleted.

Please send me a solution ASAP.

Thank you.
