### ISSUE TITLE
Problem with Database if using prefix

### ISSUE THREAD

**Issue by Feyks** [lizardmedia/product-attachments-magento2#5]
Step to reproduce :
- Installing Magento 2 with a database prefix like mg2_
- Install Product Attachment with setup:upgrade

Explaination :
- Magento is trying to find index lizardmedia_product_attachment but during the installation Magento named it {prafix}lizardmedia_product_attachment. So it's not found

Solution to avoid the problem:
- Replace the following lines :
  - in Setup/InstallSchema.php line 125 : $setup->getTable(Attachment::MAIN_TABLE),
  - in Setup/InstallSchema.php line 129 : $setup->getTable(Attachment::MAIN_TABLE),

**Comment by bartoszkubicki** [comment]
@Feyks thank you for reporting this issue. We dont use prefixes, so we didnt meet such an issue. I will fix it quickly.

**Comment by bartoszkubicki** [comment]
#6

**Comment by bartoszkubicki** [comment]
@Feyks PR is ready and it will be reviewed soon. You can also take a look at #7

**Comment by bartoszkubicki** [comment]
@Feyks fix is shipped with new release 1.0.4. Please let me know if now you can install module.

**Comment by Feyks** [comment]
I ll try to install wheni ll rebuild my magento docker.  Seeing the updated code, i think i won't have any trouble.
Thanks for your time and your module.

**Comment by bartoszkubicki** [comment]
@Feyks have you tried?
