### ISSUE TITLE
Problem with Deleting Attachments

### ISSUE THREAD

**Issue by tapasweem** [lizardmedia/product-attachments-magento2#8]
Step to reproduce the issue :

1. Created a product and uploaded the attachment and saved the product.
2. I want to delete the saved attachment. 

I am getting below error while deleting the attachment.

Fatal error: Uncaught TypeError: Return value of LizardMedia\ProductAttachment\Model\AttachmentRepository::updateAttachment() must be of the type integer, string returned in /app/code/LizardMedia/ProductAttachment/Model/AttachmentRepository.php:466 Stack trace: #0 /app/code/LizardMedia/ProductAttachment/Model/AttachmentRepository.php(325): LizardMedia\ProductAttachment\Model\AttachmentRepository->updateAttachment(Object(Model\Sample\Model\Catalog\Product\Interceptor), Object(LizardMedia\ProductAttachment\Model\Attachment), true) #1 /app/code/LizardMedia/ProductAttachment/Model/Attachment/UpdateHandler.php(55): LizardMedia\ProductAttachment\Model\AttachmentRepository->save('TestProduct002', Object(LizardMedia\ProductAttachment\Model\Attachment), true) #2 /vendor/magento/framework/EntityManager/Operation/Update/UpdateExtensions.php(49): LizardMedia\ProductAttachment\Model\Attachment\UpdateHandler->execute(Object(Model\Sample\Model\Ca in /app/code/LizardMedia/ProductAttachment/Model/AttachmentRepository.php on line 466

**Comment by bartoszkubicki** [comment]
Hi @tapasweem ,

thank you for reporting an issue. Are you sure you have actual codebase? I think I have fixed this week ago [https://github.com/lizardmedia/product-attachments-magento2/commit/b90d3e8a1d55e772ba1106e3f20fb0f89e1736e4#diff-27c68e21b5bd67c3340b9d8b4dbaf53fR450](here)

**Comment by tapasweem** [comment]
Hi @bartoszkubicki,

Thank You for your support. Now I am able to delete the attachment after adding your code changes.
